import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { CrossfadeReveal } from "@/components/crossfade-reveal";
import { DebugGrid } from "@/components/debug-grid";
import { Footer } from "@/components/footer";
import { LoadingScreen } from "@/components/loading-screen";
import { Navbar } from "@/components/navbar";
import "./globals.css";

// Runs before hydration so the initial paint already matches the right theme,
// instead of always starting light and flashing to dark a moment later. A
// saved manual choice (Navbar's toggle, localStorage) wins if one exists;
// otherwise falls back to the visitor's OS preference.
const THEME_INIT_SCRIPT = `
  try {
    var saved = localStorage.getItem("theme");
    var isDark = saved ? saved === "dark" : window.matchMedia("(prefers-color-scheme: dark)").matches;
    document.documentElement.setAttribute("data-theme", isDark ? "dark" : "light");
  } catch (e) {}
`;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <Script id="theme-init" strategy="beforeInteractive">
          {THEME_INIT_SCRIPT}
        </Script>
        {process.env.NODE_ENV === "development" && <DebugGrid />}
        <LoadingScreen />
        <div className="flex flex-col rounded-card bg-background-primary">
          <CrossfadeReveal>
            <Navbar />
          </CrossfadeReveal>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
