import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { DebugGrid } from "@/components/debug-grid";
import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {process.env.NODE_ENV === "development" && <DebugGrid />}
        <div className="flex flex-col rounded-card bg-background-primary">
          <Navbar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
